# Generated by Django 3.0.7 on 2023-05-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pis_supplier', '0003_auto_20190806_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierstatement',
            name='description',
            field=models.TextField(blank=True, max_length=65, null=True),
        ),
        migrations.AlterField(
            model_name='supplierstatement',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='supplierstatement',
            name='supplier_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=65, null=True),
        ),
    ]
